//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ingredient
    {
        public int IngredientId { get; set; }
        public Nullable<int> RecipeId { get; set; }

        [Required]
        [MinLength(1)]
        [MaxLength(50)]
        public string IngredientName { get; set; }

        [Required]
        [MinLength(1)]
        [MaxLength(25)]
        public string Amount { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
