//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Ingredient = new HashSet<Ingredient>();
            this.Method = new HashSet<Method>();
        }
    
        public int RecipeId { get; set; }

        [Required]
        [Range(0,999)]
        public Nullable<int> Time { get; set; }

        [Required]
        [MinLength(1)]
        [MaxLength(150)]
        public string Name { get; set; }

        [Required]
        [MinLength(1)]
        [MaxLength(500)]
        public string ImageUrl { get; set; }

        [Required]
        [MinLength(1)]
        [MaxLength(25)]
        public string Difficulty { get; set; }

        // Dynamically Set in the controller
        public Nullable<int> iCount { get; set; }
        public Nullable<int> mCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Method> Method { get; set; }
    }
}
